### ISSUE TITLE
Is there a reason for explicitly using SqlConnection?

### ISSUE THREAD

**Issue by jjwilliams42** [Tazmainiandevil/dapper-wrapper#1]
Great stuff - thanks for extending the functionality to include recent extension methods. 

I started working with the library, only using Postgresql. I began writing my own PostgresExecutor, only to realize that if you change one thing, it should work with either:

In SqlExecutor, you require a SqlConnection to be passed in which only works with SQL Server. Why not pass in an IDbConnection? This lets me (a Postgresql+Dapper user) pass in whatever connection I have constructed, and the next guy (A MySql user) to pass in his connection.

Unless I am missing something big, IDbConnection has the same methods available from Dapper as SqlConnection (and as NpgsqlConnection, etc...).

**Comment by Tazmainiandevil** [comment]
Initially I used the code for SQL Databases and then forked the code to try and keep it up to date, I haven't had the need to look at something else and overlooked that part of the code. Thanks for the comments and suggestion. Looking at the code I cannot see why using the IDbConnection would cause an issue. I have done some initial testing with queries and it looks like it works as expected. I'll publish a new version on nuget tonight. Please let me know if there are any issues.
