### ISSUE TITLE
Don't Require Microsoft.Data.SqlClient as a Dependency

### ISSUE THREAD

**Issue by TheAjItator** [Tazmainiandevil/dapper-wrapper#2]
A suggested enhancement would be to remove Microsoft.Data.SqlClient as a dependency or otherwise enable not having to pull in this library (and its own dependencies).  This would allow projects that want to use the Abstractions but don't use SQL Server to not need to have the library pulled in.

**Comment by Tazmainiandevil** [comment]
I guess the SQL Server part could be factored out to a separate library for (e.g. Dapper.Abstractions.Sql) so that those wanting to use SQL Server can use that and others can just use the abstractions

**Comment by TheAjItator** [comment]
Yeah, I think that would be good.  There's use-cases were using Oracle or PostgreSQL and it seems like a lot of dependencies to pull in by needing SQL Service drivers.

Please pardon the really delayed response.

**Comment by TheAjItator** [comment]
I can create a PR, however if I add an Oracle version their libraries are .NET Framework 4.6.2 or .NET Standard 2.1
Should I omit the .NET Framework version for the Oracle version as it's more of a convenience/example anyhow?

**Comment by TheAjItator** [comment]
Created PR for this issue - #4

**Comment by Tazmainiandevil** [comment]
Apologies for not getting to this sooner
